version: '3.8'

services:
  web:
    build: .
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=senha123
    ports:
      - "8069:8069"

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=senha123
    volumes:
      - odoo_db_data:/var/lib/postgresql/data

volumes:
  odoo_db_data:
